version: '3'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: dolar-mongo
    restart: unless-stopped
    networks:
      - dolar-net
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - 'dolar-mongo-data:/data/db'
  backend:
    container_name: dolar-backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - dolar-net
    ports:
      - '8888:8888'
    expose:
      - '8888'
    depends_on:
      - mongodb
volumes:
  dolar-mongo-data:
    driver: local
networks:
  dolar-net:
    driver: bridge
