version: '3'
services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: dolar-cadvisor
    restart: unless-stopped
    networks:
      - dolar-net
    ports:
      - '8080:8080'
    expose:
      - '8080'
    volumes:
      - 'dolar-cadvisor-data:/data/cadvisor'
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  redis:
    image: redis:latest
    container_name: dolar-redis
    restart: unless-stopped
    networks:
      - dolar-net
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - 'dolar-redis-data:/data/redis'
  prometheus:
    image: prom/prometheus:latest
    container_name: dolar-prometheus
    restart: unless-stopped
    networks:
      - dolar-net
    ports:
      - '9090:9090'
    expose:
      - '9090'
    volumes:
      - 'dolar-prometheus-data:/data/prometheus'
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: dolar-jaeger
    restart: unless-stopped
    networks:
      - dolar-net
    ports:
      - '6831:6831/udp'
      - '16686:16686'
    expose:
      - '6831'
    volumes:
      - 'dolar-jaeger-data:/data/jaeger'
  grafana:
    image: 'grafana/grafana'
    container_name: dolar-grafana
    restart: unless-stopped
    networks:
      - dolar-net
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - 'dolar-grafana-data:/data/grafana'
  mongodb:
    image: 'mongo:latest'
    container_name: dolar-mongo
    restart: unless-stopped
    networks:
      - dolar-net
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - 'dolar-mongo-data:/data/db'
  backend:
    container_name: dolar-backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - dolar-net
    ports:
      - '8888:8888'
    expose:
      - '8888'
    depends_on:
      - mongodb
volumes:
  dolar-mongo-data:
    driver: local
  dolar-grafana-data:
    driver: local
  dolar-jaeger-data:
    driver: local
  dolar-prometheus-data:
    driver: local
  dolar-cadvisor-data:
    driver: local
  dolar-redis-data:
    driver: local
networks:
  dolar-net:
    driver: bridge
