version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    networks:
      - dolar-net
    ports:
      - '6831:6831/udp'
      - '16686:16686'
    volumes:
      - 'dolar-jaeger-data:/data/jaeger'
  grafana:
    image: 'grafana/grafana'
    container_name: dolar-grafana
    restart: unless-stopped
    networks:
      - dolar-net
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - 'dolar-grafana-data:/data/grafana'
  mongodb:
    image: 'mongo:latest'
    container_name: dolar-mongo
    restart: unless-stopped
    networks:
      - dolar-net
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - 'dolar-mongo-data:/data/db'
  backend:
    container_name: dolar-backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - dolar-net
    ports:
      - '8888:8888'
    expose:
      - '8888'
    depends_on:
      - mongodb
volumes:
  dolar-mongo-data:
    driver: local
  dolar-grafana-data:
    driver: local
  dolar-jaeger-data:
    driver: local
networks:
  dolar-net:
    driver: bridge
