version: '3'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: local-mongo
    restart: unless-stopped
    networks:
      - local-net
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - 'local-mongo-data:/data/db'
    networks:
      - local-net
    ports:
      - '8888:8888'
    expose:
      - '8888'
    depends_on:
      - mongodb
volumes:
  local-mongo-data:
    driver: local
networks:
  local-net:
    driver: bridge
