app:
  cache-ttl: 1440 # 1 day in minutes

dolar:
  url-pattern:
    cotacaodolardia: https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoDolarDia(dataCotacao=@dataCotacao)?@dataCotacao='%s'&$top=100&$skip=0&$format=json&$select=cotacaoCompra,cotacaoVenda,dataHoraCotacao

spring:
  data:
    mongodb:
      host: @mongodb.host@
      port: @mongodb.port@
      database: @mongodb.db@
  profiles:
    active: @spring.profile.active@

server:
  port: @application.port@
  servlet:
    context-path: @application.basepath@
